spring.datasource.url: jdbc:h2:file:./camunda-h2-database

#camunda.bpm.admin-user:
 # id: demo
 # password: demo
camunda:
  bpm:
    history-level: FULL
    processEnginePlugins: org.camunda.connect.plugin.impl.ConnectProcessEnginePlugin,org.camunda.spin.plugin.impl.SpinProcessEnginePlugin
    admin-user:
      id: demo
      password: demo